name: nuxt-monorepo-template
private: true
type: module

engines:
  node: '>= 24'

devEngines:
  packageManager:
    name: pnpm
    version: 11.2.2+sha512.36e6621fad506178936455e70247b8808ef4ec25797a9f437a93281a020484e2607f6a469a22e982987c3dbb8866e3071514ab10a4a1749e06edcd1ec118436f
    onFail: download

scripts:
  prepare: husky

  clean: ruby scripts/clean.rb

  # Task to create package.json for tools that need it
  compile:packageManifests: ruby scripts/compile_package_manifests.rb

  # Workaround for:
  # - ESLint requiring a package.json
  # - Vitest to load ESM modules, as it needs to see "type": "module" in package.json
  # - Nuxt needing package.json to typecheck properly
  pnpm:devPreinstall: pnpm compile:packageManifests

  # Convenience tasks for running the same task in all packages
  build: pnpm --recursive --aggregate-output build
  dev: pnpm --recursive --aggregate-output dev

  typecheck: pnpm --parallel --aggregate-output typecheck

  test:unit:watch: pnpm --parallel --aggregate-output test:unit:watch
  test:unit: pnpm --parallel --aggregate-output test
  test:e2e:ui: pnpm --parallel --aggregate-output test
  test:e2e: pnpm --parallel --aggregate-output test

  lint: pnpm --parallel --aggregate-output lint
  lint:es: pnpm --parallel --aggregate-output lint:es
  lint:style: pnpm --parallel --aggregate-output lint:style
  lint:fix: pnpm --parallel --aggregate-output lint:fix
  lint:es:fix: pnpm --parallel --aggregate-output lint:es:fix
  lint:style:fix: pnpm --parallel --aggregate-output lint:style:fix

devDependencies:
  '@nuxt-monorepo-template/tsconfig': 'workspace:*'
  '@nuxt-monorepo-template/eslint-config': 'workspace:*'

  eslint: catalog:eslint

  husky: catalog:commit-checks
  lint-staged: catalog:commit-checks

  typescript: catalog:typescript
  jiti: catalog:typescript
  '@types/node': catalog:typescript
  type-fest: catalog:typescript

  vitest: catalog:testing

  '@pnpm/workspace.projects-reader': catalog:scripts
