name: nuxt-monorepo-template
private: true
type: module

engines:
  node: '>= 24'

devEngines:
  packageManager:
    name: pnpm
    version: 11.25.0
    onFail: download

scripts:
  prepare: husky

  clean: ruby scripts/clean.rb

  install:full: pnpm run clean --lockfile && pnpm install --lockfile-only && pnpm ci

  # Task to create package.json for tools that need it
  compile:packageManifests: ruby scripts/compile_package_manifests.rb

  # Workaround for:
  # - ESLint requiring a package.json
  # - Vitest to load ESM modules, as it needs to see "type": "module" in package.json
  # - Nuxt needing package.json to typecheck properly
  pnpm:devPreinstall: pnpm compile:packageManifests

  # Convenience tasks for running the same task in all packages
  build: pnpm --recursive --aggregate-output build
  dev: pnpm --recursive --aggregate-output dev

  typecheck: pnpm --parallel --no-bail --aggregate-output typecheck

  test:unit:watch: pnpm --parallel --no-bail --aggregate-output test:unit:watch
  test:unit: pnpm --parallel --no-bail --aggregate-output test:unit
  test:e2e:ui: pnpm --parallel --no-bail --aggregate-output test:e2e:ui
  test:e2e: pnpm --parallel --no-bail --aggregate-output test:e2e

  lint: pnpm --parallel --no-bail --aggregate-output lint
  lint:es: pnpm --parallel --no-bail --aggregate-output lint:es
  lint:style: pnpm --parallel --no-bail --aggregate-output lint:style
  lint:fix: pnpm --parallel --no-bail --aggregate-output lint:fix
  lint:es:fix: pnpm --parallel --no-bail --aggregate-output lint:es:fix
  lint:style:fix: pnpm --parallel --no-bail --aggregate-output lint:style:fix

devDependencies:
  '@nuxt-monorepo-template/tsconfig': 'workspace:*'
  '@nuxt-monorepo-template/eslint-config': 'workspace:*'

  eslint: catalog:eslint

  husky: catalog:commit-checks
  lint-staged: catalog:commit-checks

  typescript: catalog:typescript
  jiti: catalog:typescript
  '@types/node': catalog:typescript
  type-fest: catalog:typescript

  vitest: catalog:testing

  '@pnpm/workspace.projects-reader': catalog:scripts
